[project]
name = "pysim"
version = "0.1.0"
description = ""
authors = [
    {name = "Venkata Ratnam Bhumireddy",email = "58448762+venkataratnamb20@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
]

[tool.poetry]
packages = [{include = "pysim", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
