name: Git Actions Basics

on:
  push:
    branches: ["actions2602"]


jobs:
  ech:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: bash
        run: |
          echo "Hello World!"

      - name: bash script
        run: |
          cd actions2602 && bash welcome.sh