name: Git Actions Basics

on:
  push:
    branches: ["actions2602"]


jobs:
    
  welcome-from-shell:
    runs-on: ubuntu-latest
    steps:
      - name: bash
        run: |
          echo "Hello World!"
    
  welcome-from-python:
    runs-on: ubuntu-latest
    steps:
      - name: python
        run: |
          print("Python: Hello World!")
        shell: python
  
  welcom-from-bash-script:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: bash script
          run: |
            cd actions2602 && bash welcome.sh
  
  welcom-from-python-script:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: python script
          run: |
            cd actions2602 && python basics.py
            