name: Build Python package

on:
  push:
    branches: [ "pypackage" ]
    paths:
      - 'pypackage2602/**'
      - '.github/workflows/pypackage.yml'
      
  pull_request:
    branches: [ "pypackage" ]
    paths:
      - 'pypackage2602/**'
      - '.github/workflows/pypackage.yml'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                python-version: '3.10'
            - name: Cache virtualenv
              uses: actions/cache@v3
              with:
                path: venv
                key: ${{ runner.os }}-venv-${{ hashFiles('pypackage2602/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-venv-
            - name: Create and install dependencies
              run: |
                python -m venv venv
                source venv/bin/activate
                pip install --upgrade pip wheel setuptools
                pip install flake8 pytest
                if [ -f pypackage2602/requirements.txt ]; then pip install -r pypackage2602/requirements.txt; fi
            - name: Lint with flake8
              run: |
                cd pypackage2602
                echo "Running lint..."
                # stop the build if there are Python syntax errors or undefined names
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                python-version: '3.10'
            - name: Cache virtualenv
              uses: actions/cache@v3
              with:
                path: venv
                key: ${{ runner.os }}-venv-${{ hashFiles('pypackage2602/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-venv-
            - name: Activate environment and test
              run: |
                source venv/bin/activate
                cd pypackage2602/
                echo "Running test!!"
                pytest